### GET RIDER COORDINATES
GET http://localhost:3002/rider-coordinates


###GET RIDER COORDINATES 
GET http://localhost:3002/rider-coordinates/dffds324324234234234234330000rr

### POST RIDER COORDINATES
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
    "lat": 1232.23,
    "lng": 3332333.23,
    "rider": "dffds324324234234234234330000rr"
}